name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev

    - name: Build Debian Package
      run: |
        chmod +x build_deb.sh
        ./build_deb.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: onshape-to-orca-deb
        path: dist/*.deb
